# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BettingProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=30)),
                ('away', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_win', models.FloatField(default=1.0)),
                ('away_win', models.FloatField(default=1.0)),
                ('no_win', models.FloatField(default=1.0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.League')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.BettingProvider')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Sports'),
        ),
    ]
